[package]
name = "fc_wallet_exporter"
version = "0.1.0"
authors = ["Usman Saleem <usman@usmans.info>"]
edition = "2018"

[dependencies]
base64 = "0.13.0"
hex = "0.4.2"
anyhow = "1.0.33"
structopt = "0.3.13"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
